### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by francisco285** [francisco285/scratch-file.nvim#1]
- [ ] `:ScratchFile` should accept one argument which would be used as the filename to be created/opened. (that would also allow easier integration with plugins like telescope.nvim).
- [ ] Tab autocomplete for `:ScratchFile` showing all files in `~/.cache/nvim/scratch-file/` (or whatever the default directory is).
- [ ] `autocmd User ScratchFile`
- [ ] Allow use of non-floating windows
- [ ] Customization
  - [ ] Default file name
  - [ ] Default directory
  - [ ] Window type (floating/split/tab/other)
  - [ ] Window function/command
- [ ] Add LICENSE
- [ ] Enhance README
